name: UI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=./allure-results --numprocesses 2
          
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results/
          retention-days: 1

  publish-report:
    needs: run-tests  # Запускается только после run-tests
    runs-on: ubuntu-latest
    if: always()  # Выполняется даже при ошибках в run-tests

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Fix permissions
        if: always()
        run: sudo chown -R $USER:$USER .

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history
          publish_branch: gh-pages
          force_orphan: true